# Generated by Django 3.1.7 on 2021-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_apisuccessresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ApiSuccessResponse',
        ),
    ]
